services:
#    innova_wiktionary.example:
#        class: Innova\WiktionaryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    innovalangues_wiktionary:
        class: Innova\WiktionaryBundle\Manager\WiktionaryManager
