services:
    innovalangues_wiktionary:
        class: Innova\WiktionaryBundle\Manager\WiktionaryManager

    twig.extension.wiktionary:
        class: Innova\WiktionaryBundle\Twig\WiktionaryExtension
        arguments:
            "wiktionaryManager": "@innovalangues_wiktionary"
        tags:
            - { name: twig.extension }
